<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ImportGroup Label="PropertySheets" />
    <PropertyGroup Label="UserMacros" />

    <!-- dui项目，所有工程的输出公共配置 -->
    <PropertyGroup>
        <OutDir>$(SolutionDir)\..\lib\$(Platform)\</OutDir>
        <IntDir>$(SolutionDir)\build_temp\$(PlatformName)\$(ProjectName)\$(Configuration)\</IntDir>
    </PropertyGroup>    
    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <TargetName>$(ProjectName)_d</TargetName>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <TargetName>$(ProjectName)</TargetName>
    </PropertyGroup>
    
    <!-- dui项目，支持VS2026(v145)和VS2022(v143)[主分支]，支持VS2019(v142)和VS2017(v141)[develop-cpp17分支] -->
    <PropertyGroup Condition="'$(VisualStudioVersion)' == '18.0'" Label="Configuration">
        <PlatformToolset>v145</PlatformToolset>
    </PropertyGroup>
    <PropertyGroup Condition="'$(VisualStudioVersion)' == '17.0'" Label="Configuration">
        <PlatformToolset>v143</PlatformToolset>
    </PropertyGroup>
    <PropertyGroup Condition="'$(VisualStudioVersion)' == '16.0'" Label="Configuration">
        <PlatformToolset>v142</PlatformToolset>
    </PropertyGroup>
    <PropertyGroup Condition="'$(VisualStudioVersion)' == '15.0'" Label="Configuration">
        <PlatformToolset>v141</PlatformToolset>
    </PropertyGroup>

    <!-- dui项目，所有工程的SDK版本选项配置: VS2017需要设置具体的版本号，其他高版本只需要设置主版本号即可 -->
    <PropertyGroup Condition="'$(VisualStudioVersion)' != '15.0'" Label="Globals">
        <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(VisualStudioVersion)' == '15.0'" Label="Globals">
        <WindowsTargetPlatformVersion>$([Microsoft.Build.Utilities.ToolLocationHelper]::GetLatestSDKTargetPlatformVersion('Windows', '10.0'))</WindowsTargetPlatformVersion>
    </PropertyGroup>

    <!-- dui项目，所有工程的编译选项配置: MT/MTd 或者 MD/MDd (根据当前文件所在目录是否存在dui_dll.flag这个文件决定)-->
    <PropertyGroup Label="Globals">
        <DuiDllFlagFile>$(MSBuildThisFileDirectory)\dui_dll.flag</DuiDllFlagFile>
        <EnableDuiDll Condition="!Exists('$(DuiDllFlagFile)')">0</EnableDuiDll>
        <EnableDuiDll Condition="Exists('$(DuiDllFlagFile)')">1</EnableDuiDll>
    </PropertyGroup>    
    <ItemDefinitionGroup>
        <ClCompile>
            <RuntimeLibrary Condition="'$(EnableDuiDll)' == '1' And '$(Configuration)'=='Release'">MultiThreadedDll</RuntimeLibrary>
            <RuntimeLibrary Condition="'$(EnableDuiDll)' != '1' And '$(Configuration)'=='Release'">MultiThreaded</RuntimeLibrary>
            <RuntimeLibrary Condition="'$(EnableDuiDll)' == '1' And '$(Configuration)'=='Debug'">MultiThreadedDebugDll</RuntimeLibrary>
            <RuntimeLibrary Condition="'$(EnableDuiDll)' != '1' And '$(Configuration)'=='Debug'">MultiThreadedDebug</RuntimeLibrary>
        </ClCompile>
    </ItemDefinitionGroup>

    <!-- dui项目，支持VS2026和VS2022[主分支]：使用C++20标准 -->
    <ItemDefinitionGroup Condition="'$(VisualStudioVersion)' != '15.0' And '$(VisualStudioVersion)' != '16.0'">
        <ClCompile>
            <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
            <LanguageStandard>stdcpp20</LanguageStandard>
            <LanguageStandard_C>stdc17</LanguageStandard_C>
        </ClCompile>
    </ItemDefinitionGroup>

    <!-- dui项目，支持VS2019和VS2017[develop-cpp17]：使用C++17标准 -->
    <ItemDefinitionGroup Condition="'$(VisualStudioVersion)' == '15.0' Or '$(VisualStudioVersion)' == '16.0'">
        <ClCompile>
            <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
            <LanguageStandard>stdcpp17</LanguageStandard>
            <LanguageStandard_C>stdc11</LanguageStandard_C>
        </ClCompile>
    </ItemDefinitionGroup>
    
    <!-- dui项目，当使用DLL时，禁用STL的一个编译警告，并添加DLL相关的宏定义 -->
    <ItemDefinitionGroup Condition="'$(EnableDuiDll)' == '1'">
        <ClCompile>
            <DisableSpecificWarnings>%(DisableSpecificWarnings);4251</DisableSpecificWarnings>
            <PreprocessorDefinitions>DUI_DLL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
        </ClCompile>
        <ResourceCompile>
            <PreprocessorDefinitions>DUI_DLL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
        </ResourceCompile>
    </ItemDefinitionGroup>

    <!-- dui项目，自身的基础Lib名称列表，不含CEF、WebView2 -->
    <PropertyGroup Label="Globals">
        <DuiSystemLibs>opengl32.lib;Imm32.lib;comctl32.lib;shlwapi.lib;</DuiSystemLibs>
        <DuiThirdLibs Condition="'$(Configuration)'=='Debug'">zlib_d.lib;cximage_d.lib;libpng_d.lib;libwebp_d.lib</DuiThirdLibs>
        <DuiThirdLibs Condition="'$(Configuration)'=='Release'">zlib.lib;cximage.lib;libpng.lib;libwebp.lib</DuiThirdLibs>
        <DuiMainLib Condition="'$(Configuration)'=='Debug'">dui_d.lib</DuiMainLib>
        <DuiMainLib Condition="'$(Configuration)'=='Release'">dui.lib</DuiMainLib>
    </PropertyGroup>
</Project>