#ifndef UI_CORE_ZIPMANAGER_H_
#define UI_CORE_ZIPMANAGER_H_

#include "duilib/Utils/FilePath.h"
#include <string>
#include <vector>
#include <unordered_set>
#include <memory>
#include <map>
#include <cstdint>

namespace ui 
{
class ZipStreamIO;

/**ZIP archive manager
 * Notes:
 * (1) The compression algorithm supported by the Zip archive is the Deflate algorithm; other algorithms are not supported (Deflate64 is not supported either)
 * (2) When creating an archive with 7-Zip, if the custom parameter cu=on is used, an archive with file names encoded in UTF-8 can be created; if not set, the default file name encoding is the local encoding
 * (3) If a password is set, the traditional password encryption algorithm must be used, otherwise the archive cannot be extracted. (Use a password in the "ZIP legacy encryption" mode or the "ZipCrypto" algorithm)
 */
class DUILIB_API ZipManager
{
public:
    ZipManager();
    ~ZipManager();
    ZipManager(const ZipManager&) = delete;
    ZipManager& operator = (const ZipManager&) = delete;

public:
    /** Determine whether a zip archive is currently used
     * @return Returns true if a zip archive is used as the resource, false for the normal directory mode
     */
    bool IsUseZip() const;

#ifdef DUILIB_BUILD_FOR_WIN
    /** Open an in-memory archive resource
     * @param[in] hModule Resource handle; if nullptr, it represents the module handle of the current executable
     * @param[in] resourceName Resource name, generated by the MAKEINTRESOURCE macro
     * @param[in] resourceType Resource type, the name of the custom-imported resource type
     * @param[in] password Archive password
     */
    bool OpenResZip(HMODULE hModule, LPCTSTR resourceName, LPCTSTR resourceType, const DString& password);
#endif

    /** Open a local file archive resource
     * @param[in] path Archive file path
     * @param[in] password Archive password
     */
    bool OpenZipFile(const FilePath& path, const DString& password);

    /** Open an embedded in-memory resource archive (Qt qrc style; no zip container).
     * The data is generated at build time by the embed_resources tool:
     *   [magic "DUIR" u32][version u32][count u32]
     *   count x [u32 pathLen][path UTF-8][u64 dataOffset][u64 dataLen]
     *   [data blocks]
     * @param[in] pData Pointer to the embedded resource data
     * @param[in] nSize Size of the embedded resource data
     * @return Returns true if the memory resource archive was opened successfully
     * @note The data pointer must remain valid for the lifetime of the ZipManager
     *       (e.g. a static array embedded in the executable).
     */
    bool OpenMemoryArchive(const uint8_t* pData, size_t nSize);

    /** Get the content in the archive into memory
     * @param [in] path The path of the file to get (path inside the archive)
     * @param [out] fileData The path of the file to get
     */
    bool GetZipData(const FilePath& path, std::vector<unsigned char>& fileData) const;

    /** Determine whether the resource exists in the zip
     * @param[in] path The resource path to check (path inside the archive)
     */
    bool IsZipResExist(const FilePath& path) const;

    /** Get the list of file names in the specified directory
    * @param [in] dirPath Directory name (path inside the archive)
    * @param [out] fileList Returns the file list in this directory
    */
    bool GetZipFileList(const FilePath& dirPath, std::vector<DString>& fileList) const;

    /** Close the archive
    */
    void CloseResZip();

private:
    /** Normalize a Zip-format path ('\\' is replaced with '/')
    */
    void NormalizeZipFilePath(std::string& innerFilePath) const;
    void NormalizeZipFilePath(std::wstring& innerFilePath) const;

    /** Locate a file in the archive
    * @param [in] normalizePath File path
    * @param [out] filePathA Returns the file path inside the archive (MBCS or UTF8 encoding)
    * @return Returns true on successful location, otherwise false
    */
    bool LocateFile(const FilePath& normalizePath, std::string& filePathA) const;

    /** Get the path inside the archive (convert the string encoding)
    * @param [in] szInZipFilePath The file path to get (path inside the archive)
    * @param [in] bUtf8 true means UTF8 encoding, otherwise Ansi encoding
    */
    DString GetZipFilePath(const char* szInZipFilePath, bool bUtf8) const;

    /** Normalize a path for the memory archive index lookup (lowercase, '/' separators)
    */
    DStringW NormalizeMemoryPath(const FilePath& path) const;

private:

    /** The handle of the opened archive
    */
    void* m_hzip;

    /** Whether an embedded memory resource archive is in use (Qt qrc style, no zip)
    */
    bool m_bUseMemory;

    /** The data of the embedded memory resource archive
    */
    const uint8_t* m_pMemoryData;

    /** The size of the embedded memory resource archive
    */
    size_t m_memoryDataSize;

    /** The data range of one entry in the memory archive
    */
    struct MemoryResData
    {
        size_t nOffset;
        size_t nSize;
    };

    /** Path index of the memory archive (key: normalized lowercase path, '/' separators)
    */
    std::map<DStringW, MemoryResData> m_memoryIndex;

    /** The extraction password of the archive
    */
    DString m_password;

    /** The read interface of the memory stream
    */
    std::unique_ptr<ZipStreamIO> m_pZipStreamIO;

    /** Path cache
    */
    mutable std::unordered_set<DStringW> m_zipPathCache;
};

}
#endif //UI_CORE_ZIPMANAGER_H_
