#include "dui/Core/UiColors.h"

// Include all the basic type data structures, to test for compilation errors etc. during the development stage
#include "dui/Core/UiColor.h"
#include "dui/Core/UiFont.h"
#include "dui/Core/UiRect.h"
#include "dui/Core/UiSize.h"
#include "dui/Core/UiPoint.h"

namespace ui 
{
namespace UiColors
{
    /** Common color values and their corresponding string constants
    */
    void GetUiColorsString(std::vector<std::pair<DString, int32_t>>& uiColors)
    {
        uiColors = {
                    {DUI_T("AliceBlue"),UiColors::AliceBlue},
                    {DUI_T("AntiqueWhite"),UiColors::AntiqueWhite},
                    {DUI_T("Aqua"),UiColors::Aqua},
                    {DUI_T("Aquamarine"),UiColors::Aquamarine},
                    {DUI_T("Azure"),UiColors::Azure},
                    {DUI_T("Beige"),UiColors::Beige},
                    {DUI_T("Bisque"),UiColors::Bisque},
                    {DUI_T("Black"),UiColors::Black},
                    {DUI_T("BlanchedAlmond"),UiColors::BlanchedAlmond},
                    {DUI_T("Blue"),UiColors::Blue},
                    {DUI_T("BlueViolet"),UiColors::BlueViolet},
                    {DUI_T("Brown"),UiColors::Brown},
                    {DUI_T("BurlyWood"),UiColors::BurlyWood},
                    {DUI_T("CadetBlue"),UiColors::CadetBlue},
                    {DUI_T("Chartreuse"),UiColors::Chartreuse},
                    {DUI_T("Chocolate"),UiColors::Chocolate},
                    {DUI_T("Coral"),UiColors::Coral},
                    {DUI_T("CornflowerBlue"),UiColors::CornflowerBlue},
                    {DUI_T("Cornsilk"),UiColors::Cornsilk},
                    {DUI_T("Crimson"),UiColors::Crimson},
                    {DUI_T("Cyan"),UiColors::Cyan},
                    {DUI_T("DarkBlue"),UiColors::DarkBlue},
                    {DUI_T("DarkCyan"),UiColors::DarkCyan},
                    {DUI_T("DarkGoldenrod"),UiColors::DarkGoldenrod},
                    {DUI_T("DarkGray"),UiColors::DarkGray},
                    {DUI_T("DarkGreen"),UiColors::DarkGreen},
                    {DUI_T("DarkKhaki"),UiColors::DarkKhaki},
                    {DUI_T("DarkMagenta"),UiColors::DarkMagenta},
                    {DUI_T("DarkOliveGreen"),UiColors::DarkOliveGreen},
                    {DUI_T("DarkOrange"),UiColors::DarkOrange},
                    {DUI_T("DarkOrchid"),UiColors::DarkOrchid},
                    {DUI_T("DarkRed"),UiColors::DarkRed},
                    {DUI_T("DarkSalmon"),UiColors::DarkSalmon},
                    {DUI_T("DarkSeaGreen"),UiColors::DarkSeaGreen},
                    {DUI_T("DarkSlateBlue"),UiColors::DarkSlateBlue},
                    {DUI_T("DarkSlateGray"),UiColors::DarkSlateGray},
                    {DUI_T("DarkTurquoise"),UiColors::DarkTurquoise},
                    {DUI_T("DarkViolet"),UiColors::DarkViolet},
                    {DUI_T("DeepPink"),UiColors::DeepPink},
                    {DUI_T("DeepSkyBlue"),UiColors::DeepSkyBlue},
                    {DUI_T("DimGray"),UiColors::DimGray},
                    {DUI_T("DodgerBlue"),UiColors::DodgerBlue},
                    {DUI_T("Firebrick"),UiColors::Firebrick},
                    {DUI_T("FloralWhite"),UiColors::FloralWhite},
                    {DUI_T("ForestGreen"),UiColors::ForestGreen},
                    {DUI_T("Fuchsia"),UiColors::Fuchsia},
                    {DUI_T("Gainsboro"),UiColors::Gainsboro},
                    {DUI_T("GhostWhite"),UiColors::GhostWhite},
                    {DUI_T("Gold"),UiColors::Gold},
                    {DUI_T("Goldenrod"),UiColors::Goldenrod},
                    {DUI_T("Gray"),UiColors::Gray},
                    {DUI_T("Green"),UiColors::Green},
                    {DUI_T("GreenYellow"),UiColors::GreenYellow},
                    {DUI_T("Honeydew"),UiColors::Honeydew},
                    {DUI_T("HotPink"),UiColors::HotPink},
                    {DUI_T("IndianRed"),UiColors::IndianRed},
                    {DUI_T("Indigo"),UiColors::Indigo},
                    {DUI_T("Ivory"),UiColors::Ivory},
                    {DUI_T("Khaki"),UiColors::Khaki},
                    {DUI_T("Lavender"),UiColors::Lavender},
                    {DUI_T("LavenderBlush"),UiColors::LavenderBlush},
                    {DUI_T("LawnGreen"),UiColors::LawnGreen},
                    {DUI_T("LemonChiffon"),UiColors::LemonChiffon},
                    {DUI_T("LightBlue"),UiColors::LightBlue},
                    {DUI_T("LightCoral"),UiColors::LightCoral},
                    {DUI_T("LightCyan"),UiColors::LightCyan},
                    {DUI_T("LightGoldenrodYellow"),UiColors::LightGoldenrodYellow},
                    {DUI_T("LightGray"),UiColors::LightGray},
                    {DUI_T("LightGreen"),UiColors::LightGreen},
                    {DUI_T("LightPink"),UiColors::LightPink},
                    {DUI_T("LightSalmon"),UiColors::LightSalmon},
                    {DUI_T("LightSeaGreen"),UiColors::LightSeaGreen},
                    {DUI_T("LightSkyBlue"),UiColors::LightSkyBlue},
                    {DUI_T("LightSlateGray"),UiColors::LightSlateGray},
                    {DUI_T("LightSteelBlue"),UiColors::LightSteelBlue},
                    {DUI_T("LightYellow"),UiColors::LightYellow},
                    {DUI_T("Lime"),UiColors::Lime},
                    {DUI_T("LimeGreen"),UiColors::LimeGreen},
                    {DUI_T("Linen"),UiColors::Linen},
                    {DUI_T("Magenta"),UiColors::Magenta},
                    {DUI_T("Maroon"),UiColors::Maroon},
                    {DUI_T("MediumAquamarine"),UiColors::MediumAquamarine},
                    {DUI_T("MediumBlue"),UiColors::MediumBlue},
                    {DUI_T("MediumOrchid"),UiColors::MediumOrchid},
                    {DUI_T("MediumPurple"),UiColors::MediumPurple},
                    {DUI_T("MediumSeaGreen"),UiColors::MediumSeaGreen},
                    {DUI_T("MediumSlateBlue"),UiColors::MediumSlateBlue},
                    {DUI_T("MediumSpringGreen"),UiColors::MediumSpringGreen},
                    {DUI_T("MediumTurquoise"),UiColors::MediumTurquoise},
                    {DUI_T("MediumVioletRed"),UiColors::MediumVioletRed},
                    {DUI_T("MidnightBlue"),UiColors::MidnightBlue},
                    {DUI_T("MintCream"),UiColors::MintCream},
                    {DUI_T("MistyRose"),UiColors::MistyRose},
                    {DUI_T("Moccasin"),UiColors::Moccasin},
                    {DUI_T("NavajoWhite"),UiColors::NavajoWhite},
                    {DUI_T("Navy"),UiColors::Navy},
                    {DUI_T("OldLace"),UiColors::OldLace},
                    {DUI_T("Olive"),UiColors::Olive},
                    {DUI_T("OliveDrab"),UiColors::OliveDrab},
                    {DUI_T("Orange"),UiColors::Orange},
                    {DUI_T("OrangeRed"),UiColors::OrangeRed},
                    {DUI_T("Orchid"),UiColors::Orchid},
                    {DUI_T("PaleGoldenrod"),UiColors::PaleGoldenrod},
                    {DUI_T("PaleGreen"),UiColors::PaleGreen},
                    {DUI_T("PaleTurquoise"),UiColors::PaleTurquoise},
                    {DUI_T("PaleVioletRed"),UiColors::PaleVioletRed},
                    {DUI_T("PapayaWhip"),UiColors::PapayaWhip},
                    {DUI_T("PeachPuff"),UiColors::PeachPuff},
                    {DUI_T("Peru"),UiColors::Peru},
                    {DUI_T("Pink"),UiColors::Pink},
                    {DUI_T("Plum"),UiColors::Plum},
                    {DUI_T("PowderBlue"),UiColors::PowderBlue},
                    {DUI_T("Purple"),UiColors::Purple},
                    {DUI_T("Red"),UiColors::Red},
                    {DUI_T("RosyBrown"),UiColors::RosyBrown},
                    {DUI_T("RoyalBlue"),UiColors::RoyalBlue},
                    {DUI_T("SaddleBrown"),UiColors::SaddleBrown},
                    {DUI_T("Salmon"),UiColors::Salmon},
                    {DUI_T("SandyBrown"),UiColors::SandyBrown},
                    {DUI_T("SeaGreen"),UiColors::SeaGreen},
                    {DUI_T("SeaShell"),UiColors::SeaShell},
                    {DUI_T("Sienna"),UiColors::Sienna},
                    {DUI_T("Silver"),UiColors::Silver},
                    {DUI_T("SkyBlue"),UiColors::SkyBlue},
                    {DUI_T("SlateBlue"),UiColors::SlateBlue},
                    {DUI_T("SlateGray"),UiColors::SlateGray},
                    {DUI_T("Snow"),UiColors::Snow},
                    {DUI_T("SpringGreen"),UiColors::SpringGreen},
                    {DUI_T("SteelBlue"),UiColors::SteelBlue},
                    {DUI_T("Tan"),UiColors::Tan},
                    {DUI_T("Teal"),UiColors::Teal},
                    {DUI_T("Thistle"),UiColors::Thistle},
                    {DUI_T("Tomato"),UiColors::Tomato},
                    {DUI_T("Transparent"),UiColors::Transparent},
                    {DUI_T("Turquoise"),UiColors::Turquoise},
                    {DUI_T("Violet"),UiColors::Violet},
                    {DUI_T("Wheat"),UiColors::Wheat},
                    {DUI_T("White"),UiColors::White},
                    {DUI_T("WhiteSmoke"),UiColors::WhiteSmoke},
                    {DUI_T("Yellow"),UiColors::Yellow},
                    {DUI_T("YellowGreen"),UiColors::YellowGreen}
                    };
    }
}// namespace UiColors
} // namespace ui

