#include "dui/Core/UiColors.h"

// Include all the basic type data structures, to test for compilation errors etc. during the development stage
#include "dui/Core/UiColor.h"
#include "dui/Core/UiFont.h"
#include "dui/Core/UiRect.h"
#include "dui/Core/UiSize.h"
#include "dui/Core/UiPoint.h"

namespace ui 
{
namespace UiColors
{
    /** Common color values and their corresponding string constants
    */
    void GetUiColorsString(std::vector<std::pair<std::string, int32_t>>& uiColors)
    {
        uiColors = {
                    {"AliceBlue",UiColors::AliceBlue},
                    {"AntiqueWhite",UiColors::AntiqueWhite},
                    {"Aqua",UiColors::Aqua},
                    {"Aquamarine",UiColors::Aquamarine},
                    {"Azure",UiColors::Azure},
                    {"Beige",UiColors::Beige},
                    {"Bisque",UiColors::Bisque},
                    {"Black",UiColors::Black},
                    {"BlanchedAlmond",UiColors::BlanchedAlmond},
                    {"Blue",UiColors::Blue},
                    {"BlueViolet",UiColors::BlueViolet},
                    {"Brown",UiColors::Brown},
                    {"BurlyWood",UiColors::BurlyWood},
                    {"CadetBlue",UiColors::CadetBlue},
                    {"Chartreuse",UiColors::Chartreuse},
                    {"Chocolate",UiColors::Chocolate},
                    {"Coral",UiColors::Coral},
                    {"CornflowerBlue",UiColors::CornflowerBlue},
                    {"Cornsilk",UiColors::Cornsilk},
                    {"Crimson",UiColors::Crimson},
                    {"Cyan",UiColors::Cyan},
                    {"DarkBlue",UiColors::DarkBlue},
                    {"DarkCyan",UiColors::DarkCyan},
                    {"DarkGoldenrod",UiColors::DarkGoldenrod},
                    {"DarkGray",UiColors::DarkGray},
                    {"DarkGreen",UiColors::DarkGreen},
                    {"DarkKhaki",UiColors::DarkKhaki},
                    {"DarkMagenta",UiColors::DarkMagenta},
                    {"DarkOliveGreen",UiColors::DarkOliveGreen},
                    {"DarkOrange",UiColors::DarkOrange},
                    {"DarkOrchid",UiColors::DarkOrchid},
                    {"DarkRed",UiColors::DarkRed},
                    {"DarkSalmon",UiColors::DarkSalmon},
                    {"DarkSeaGreen",UiColors::DarkSeaGreen},
                    {"DarkSlateBlue",UiColors::DarkSlateBlue},
                    {"DarkSlateGray",UiColors::DarkSlateGray},
                    {"DarkTurquoise",UiColors::DarkTurquoise},
                    {"DarkViolet",UiColors::DarkViolet},
                    {"DeepPink",UiColors::DeepPink},
                    {"DeepSkyBlue",UiColors::DeepSkyBlue},
                    {"DimGray",UiColors::DimGray},
                    {"DodgerBlue",UiColors::DodgerBlue},
                    {"Firebrick",UiColors::Firebrick},
                    {"FloralWhite",UiColors::FloralWhite},
                    {"ForestGreen",UiColors::ForestGreen},
                    {"Fuchsia",UiColors::Fuchsia},
                    {"Gainsboro",UiColors::Gainsboro},
                    {"GhostWhite",UiColors::GhostWhite},
                    {"Gold",UiColors::Gold},
                    {"Goldenrod",UiColors::Goldenrod},
                    {"Gray",UiColors::Gray},
                    {"Green",UiColors::Green},
                    {"GreenYellow",UiColors::GreenYellow},
                    {"Honeydew",UiColors::Honeydew},
                    {"HotPink",UiColors::HotPink},
                    {"IndianRed",UiColors::IndianRed},
                    {"Indigo",UiColors::Indigo},
                    {"Ivory",UiColors::Ivory},
                    {"Khaki",UiColors::Khaki},
                    {"Lavender",UiColors::Lavender},
                    {"LavenderBlush",UiColors::LavenderBlush},
                    {"LawnGreen",UiColors::LawnGreen},
                    {"LemonChiffon",UiColors::LemonChiffon},
                    {"LightBlue",UiColors::LightBlue},
                    {"LightCoral",UiColors::LightCoral},
                    {"LightCyan",UiColors::LightCyan},
                    {"LightGoldenrodYellow",UiColors::LightGoldenrodYellow},
                    {"LightGray",UiColors::LightGray},
                    {"LightGreen",UiColors::LightGreen},
                    {"LightPink",UiColors::LightPink},
                    {"LightSalmon",UiColors::LightSalmon},
                    {"LightSeaGreen",UiColors::LightSeaGreen},
                    {"LightSkyBlue",UiColors::LightSkyBlue},
                    {"LightSlateGray",UiColors::LightSlateGray},
                    {"LightSteelBlue",UiColors::LightSteelBlue},
                    {"LightYellow",UiColors::LightYellow},
                    {"Lime",UiColors::Lime},
                    {"LimeGreen",UiColors::LimeGreen},
                    {"Linen",UiColors::Linen},
                    {"Magenta",UiColors::Magenta},
                    {"Maroon",UiColors::Maroon},
                    {"MediumAquamarine",UiColors::MediumAquamarine},
                    {"MediumBlue",UiColors::MediumBlue},
                    {"MediumOrchid",UiColors::MediumOrchid},
                    {"MediumPurple",UiColors::MediumPurple},
                    {"MediumSeaGreen",UiColors::MediumSeaGreen},
                    {"MediumSlateBlue",UiColors::MediumSlateBlue},
                    {"MediumSpringGreen",UiColors::MediumSpringGreen},
                    {"MediumTurquoise",UiColors::MediumTurquoise},
                    {"MediumVioletRed",UiColors::MediumVioletRed},
                    {"MidnightBlue",UiColors::MidnightBlue},
                    {"MintCream",UiColors::MintCream},
                    {"MistyRose",UiColors::MistyRose},
                    {"Moccasin",UiColors::Moccasin},
                    {"NavajoWhite",UiColors::NavajoWhite},
                    {"Navy",UiColors::Navy},
                    {"OldLace",UiColors::OldLace},
                    {"Olive",UiColors::Olive},
                    {"OliveDrab",UiColors::OliveDrab},
                    {"Orange",UiColors::Orange},
                    {"OrangeRed",UiColors::OrangeRed},
                    {"Orchid",UiColors::Orchid},
                    {"PaleGoldenrod",UiColors::PaleGoldenrod},
                    {"PaleGreen",UiColors::PaleGreen},
                    {"PaleTurquoise",UiColors::PaleTurquoise},
                    {"PaleVioletRed",UiColors::PaleVioletRed},
                    {"PapayaWhip",UiColors::PapayaWhip},
                    {"PeachPuff",UiColors::PeachPuff},
                    {"Peru",UiColors::Peru},
                    {"Pink",UiColors::Pink},
                    {"Plum",UiColors::Plum},
                    {"PowderBlue",UiColors::PowderBlue},
                    {"Purple",UiColors::Purple},
                    {"Red",UiColors::Red},
                    {"RosyBrown",UiColors::RosyBrown},
                    {"RoyalBlue",UiColors::RoyalBlue},
                    {"SaddleBrown",UiColors::SaddleBrown},
                    {"Salmon",UiColors::Salmon},
                    {"SandyBrown",UiColors::SandyBrown},
                    {"SeaGreen",UiColors::SeaGreen},
                    {"SeaShell",UiColors::SeaShell},
                    {"Sienna",UiColors::Sienna},
                    {"Silver",UiColors::Silver},
                    {"SkyBlue",UiColors::SkyBlue},
                    {"SlateBlue",UiColors::SlateBlue},
                    {"SlateGray",UiColors::SlateGray},
                    {"Snow",UiColors::Snow},
                    {"SpringGreen",UiColors::SpringGreen},
                    {"SteelBlue",UiColors::SteelBlue},
                    {"Tan",UiColors::Tan},
                    {"Teal",UiColors::Teal},
                    {"Thistle",UiColors::Thistle},
                    {"Tomato",UiColors::Tomato},
                    {"Transparent",UiColors::Transparent},
                    {"Turquoise",UiColors::Turquoise},
                    {"Violet",UiColors::Violet},
                    {"Wheat",UiColors::Wheat},
                    {"White",UiColors::White},
                    {"WhiteSmoke",UiColors::WhiteSmoke},
                    {"Yellow",UiColors::Yellow},
                    {"YellowGreen",UiColors::YellowGreen}
                    };
    }
}// namespace UiColors
} // namespace ui

