#ifndef UI_CORE_MEMORY_RESOURCE_MANAGER_H_
#define UI_CORE_MEMORY_RESOURCE_MANAGER_H_

#include "dui/Utils/FilePath.h"
#include <string>
#include <vector>
#include <map>
#include <cstdint>

namespace ui 
{
/**Manager for embedded resources, accessed directly from memory.
 * The resource data is generated by tools/embed_resources.cpp as a custom
 * binary blob: [magic "DUIR"][version][count] + index + data blocks.
 */
class DUI_API MemoryResourceManager
{
public:
    MemoryResourceManager();
    ~MemoryResourceManager();
    MemoryResourceManager(const MemoryResourceManager&) = delete;
    MemoryResourceManager& operator = (const MemoryResourceManager&) = delete;

public:
     /** Determine whether embedded resources are currently used
      * @return Returns true if embedded resources are used, false for local files
     */
    bool IsOpen() const;

     /** Open embedded resources, accessed directly from memory.
     * The data is generated at build time by the embed_resources tool:
     *   [magic "DUIR" u32][version u32][count u32]
     *   count x [u32 pathLen][path UTF-8][u64 dataOffset][u64 dataLen]
     *   [data blocks]
     * @param[in] pData Pointer to the embedded resource data
     * @param[in] nSize Size of the embedded resource data
     * @return Returns true if the embedded resources were opened successfully
     * @note The data pointer must remain valid for the lifetime of the manager
     *       (e.g. a static array embedded in the executable).
     */
    bool Open(const uint8_t* pData, size_t nSize);

     /** Get embedded resource content into memory
     * @param [in] path The path of the file to get
     * @param [out] fileData The file content
     */
    bool GetData(const FilePath& path, std::vector<unsigned char>& fileData) const;

     /** Determine whether an embedded resource exists
     * @param[in] path The resource path to check
     */
    bool IsDataExist(const FilePath& path) const;

     /** Get the list of embedded resource file names in the specified directory
     * @param [in] dirPath Directory name
    * @param [out] fileList Returns the file list in this directory
    */
    bool GetFileList(const FilePath& dirPath, std::vector<std::string>& fileList) const;

     /** Close the embedded resources
    */
    void Close();

private:
     /** Normalize a resource path ('\\' is replaced with '/')
    */
    void NormalizePath(std::string& innerFilePath) const;
    void NormalizePath(std::wstring& innerFilePath) const;

     /** Normalize a path for the embedded resource index lookup (lowercase, '/' separators)
    */
    std::wstring NormalizeMemoryPath(const FilePath& path) const;

private:
     /** Whether embedded resources are in use
    */
    bool m_bUseMemory;

     /** The data of the embedded resources
    */
    const uint8_t* m_pMemoryData;

     /** The size of the embedded resources
    */
    size_t m_memoryDataSize;

     /** The data range of one embedded resource
    */
    struct MemoryResData
    {
        size_t nOffset;
        size_t nSize;
    };

     /** Path index of the embedded resources (key: normalized lowercase path, '/' separators)
    */
    std::map<std::wstring, MemoryResData> m_memoryIndex;
};

}
#endif //UI_CORE_MEMORY_RESOURCE_MANAGER_H_
