#ifndef UI_CONTROL_HOTKEY_H_
#define UI_CONTROL_HOTKEY_H_

#include "duilib/Box/HBox.h"

namespace ui
{
class HotKeyRichEdit;

/** Hotkey control
*/
class DUILIB_API HotKey: public HBox
{
    typedef HBox BaseClass;
public:
    explicit HotKey(Window* pWindow);
    virtual ~HotKey() override;

    /** Get the control type
    */
    virtual DString GetType() const override;

    /** Set attributes
    */
    virtual void SetAttribute(const DString& strName, const DString& strValue) override;

    /** Let the control get the focus
     */
    virtual void SetFocus() override;

public:
    /** Set the hotkey
    * @param [in] wVirtualKeyCode Virtual key code, such as VK_DOWN, etc., see: https://learn.microsoft.com/zh-cn/windows/win32/inputdev/virtual-key-codes
    * @param [in] wModifiers The modifier key flag of the hotkey, see the values of the HotKeyModifiers enum type
    */
    void SetHotKey(uint8_t wVirtualKeyCode, uint8_t wModifiers);

    /** Get the hotkey
    * @param [out] wVirtualKeyCode Virtual key code, such as VK_DOWN, etc.
    * @param [out] wModifiers The modifier key flag of the hotkey, see the values of the HotKeyModifiers enum type
    */
    void GetHotKey(uint8_t& wVirtualKeyCode, uint8_t& wModifiers) const;

    /** Set the hotkey value [generated by MAKEWORD(wVirtualKeyCode, wModifiers)]
    * @param [in] dwHotKey The high 8 bits are wModifiers, and the low 8 bits are wVirtualKeyCode
    */
    void SetHotKey(uint16_t dwHotKey);

    /** Get the hotkey value [generated by MAKEWORD(wVirtualKeyCode, wModifiers)]
    * @return The hotkey value, the high 8 bits are wModifiers, and the low 8 bits are wVirtualKeyCode
    */
    uint16_t GetHotKey() const;

    /** Get the display name of the hotkey, such as "Ctrl + C", etc.
    */
    DString GetHotKeyName() const;

    /** Set the hotkey according to the display name
    * @param [in] hotKeyName The hotkey name, such as "Ctrl + C", etc.
    */
    bool SetHotKeyName(const DString& hotKeyName);

public:
    /** Get the display name of the key
    * @param [in] wVirtualKeyCode Virtual key code, such as VK_DOWN, etc.
    * @param [in] fExtended If the virtual key code is an extended key, it is true; otherwise it is false.
    */
    static DString GetKeyName(uint8_t wVirtualKeyCode, bool fExtended);

protected:

    //Initialization
    virtual void OnInit() override;

private:
    /** The interface of the edit box control
    */
    HotKeyRichEdit* m_pRichEdit;
};

}//namespace ui

#endif //UI_CONTROL_HOTKEY_H_
